server:
  port: 8888

spring:
  application:
    name: demo-rabbit-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/BrunoMendes97/demo-rabbit-configs
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}